package by.epam.task3.halavin.dao.tags;

public enum FoodTags {
    FOOD, IMAGINE, INGREDIENT, INGREDIENTSFORCHOOSE, ADDITIONALINGREDIENT, FOODID, NAME, PORTION, PRICE,
    INGREDIENTFORCHOOSE, INGRNAME,PRICEWITHINGR,ADDITIONALPRICE,ADDITIONALNAME,CATEGORY
}
